name: MAUI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  Build_Android:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Build Android App
        run: |
          dotnet build ./src -f net6.0-android

  Build_iOS_MacCatalyst:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Build iOS App
        run: |
          dotnet build ./src -f net6.0-ios

      - name: Build MacCatalyst App
        run: |
          dotnet build ./src -f net6.0-maccatalyst

  Build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Build Windows App
        run: |
          dotnet build ./src -f net6.0-windows10.0.19041

