name: MAUI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  Build_Android:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Install .NET 6.0.2-preview.22055.15 + .NET MAUI Workload
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.200-preview.22055.15 --quality preview
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Build Android App
        run: |
          dotnet build ./src -f net6.0-android

  Build_iOS:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Install .NET 6.0.2-preview.22055.15 + .NET MAUI Workload
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.200-preview.22055.15 --quality preview
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build ./src -f net6.0-ios
          
  Build_MacCatalyst:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Install .NET 6.0.2-preview.22055.15 + .NET MAUI Workload
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.200-preview.22055.15 --quality preview
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build ./src -f net6.0-maccatalyst

  Build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install .NET 6.0.2-preview.22055.15 + .NET MAUI Workload
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.200-preview.22055.15 --quality preview
          dotnet workload install maui

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Maui Check
        run: |
          dotnet tool install -g Redth.Net.Maui.Check
          maui-check --non-interactive --fix --ci --skip xcode --skip VisualStudioWindowsCheckup

      - name: Restore NuGet
        run: |
          dotnet restore ./src
      - name: Build Windows App
        run: |
          dotnet build ./src
